update docs

diff --git a/ollama-dependencies/ConfigMap.yaml b/ollama-dependencies/ConfigMap.yaml
--- a/ollama-dependencies/ConfigMap.yaml
+++ b/ollama-dependencies/ConfigMap.yaml
@@ -31,22 +31,20 @@ data:
         return $exit_code
     }
 
+    check_kubeapi_availability() {
+        log "Checking Kubernetes API availability..."
+        retry_command kubectl version --request-timeout=5s
+        if [ $? -ne 0 ]; then
+            log "Error: Kubernetes API server is not available. Exiting."
+            exit 1
+        fi
+        log "Kubernetes API server is available."
+    }
+
     get_secret_value() {
         local field=$1
         retry_command kubectl get secret fortiweb-login-secret -o jsonpath="{.data.$field}" | base64 -d
     }
-
-    log "Fetching credentials from secret..."
-    USERNAME=$(get_secret_value username)
-    PASSWORD=$(get_secret_value password)
-
-    if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
-        log "Error: Could not retrieve username or password from the secret."
-        exit 1
-    fi
-
-    log "Successfully retrieved credentials. Generating token..."
-    TOKEN=$(echo "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\",\"vdom\":\"root\"}" | base64 | tr -d "\\n")
 
     perform_request() {
         local method=$1
@@ -61,6 +59,22 @@ data:
             $headers \
             $data
     }
+
+    log "Starting script..."
+
+    check_kubeapi_availability
+
+    log "Fetching credentials from secret..."
+    USERNAME=$(get_secret_value username)
+    PASSWORD=$(get_secret_value password)
+
+    if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
+        log "Error: Could not retrieve username or password from the secret."
+        exit 1
+    fi
+
+    log "Successfully retrieved credentials. Generating token..."
+    TOKEN=$(echo "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\",\"vdom\":\"root\"}" | base64 | tr -d "\\n")
 
     log "Uploading OpenAPI schema file..."
     perform_request "POST" "https://10.0.0.4:443/api/v2.0/waf/openapi.openapischemafile" \
@@ -88,4 +102,3 @@ data:
         "--data-binary '{\"data\":{\"name\":\"ollama\",\"client-management\":\"enable\",\"amf3-protocol-detection\":\"disable\",\"mobile-app-identification\":\"disable\",\"token-header\":\"Jwt-Token\",\"ip-intelligence\":\"disable\",\"fortigate-quarantined-ips\":\"disable\",\"quarantined-ip-action\":\"alert\",\"quarantined-ip-severity\":\"High\",\"rdt-reason\":\"disable\",\"openapi-validation-policy\":\"ollama\"}}'"
 
     log "Script completed successfully."
-
